sudo: required
language: node_js
node_js:
  - "6.1"
install:
  - "npm install"
script:
  - ./build.sh
  - gulp
  - ./deploy.sh
env:
  global:
    - GITHUB_REPO: "open-curriculum/oerschema"
    - secure: "OpyLevECRhC+qfPgWaktmvEkyExXic2nPzKmey26I/nZVO2qgIoqukrUwq3raTlBRq6fA2B8bvKuyBTNsStT9s4nyvDOa0b2aA8pBR/ek+04PHNCIqK51N35TkeripelT/5+iwUjRU9XDYG6GbghJWrNuam6lCjHT4ZFgT8dqPUFvDR+dZIvHBFun111BAkkmI9Gwok7bwj49qxAml+JVGX9D9bUKMgT+UNO2hI8jQdYme48rgN3yiRNWQW66walTWUO8qZ9Ha35LWbtHlop/hIWY9rqY5/XjF8793mYoYtdqA2bh657icRPw4gfgheXbCFxg5NaLkhcbEjgtCRbWLYRI8y8lojOiBxirLE+LflOus0zXHjYxAwZAwvWWEQhgHzkzDjcNszVXrviQ9/KSQgGtOKfpuG0bKI23zcqmASx0lTuoYWep/aca7ndK+DYOONe8gYEP8YV4KyxFWmXixFey2vPPH08/o3m6mhqfk/KPzg5rVYQPLNRlYml1xm+Sur1jzqQwt3u6wTy/DCvvliGCzNZ6HbUq9lcDF1zan5HvtJZU8JDAoWuwYK/gsNUCH5tIbPBaFm40teDhTBnwPFz/NWg2bcc71uvBC3o5gIj0GUBEKJDVBoU6SKnUHflgOKRMb/4b3LTJ5mSwjn4TMtjoG0EgXYIcRmW8uMUo+I="
branches:
  only:
    - "master"